src/Entity/Project.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\ProjectRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Contract\Entity\TranslatableInterface;
use Knp\DoctrineBehaviors\Model\Translatable\TranslatableTrait;
use Knp\DoctrineBehaviors\Contract\Entity\TranslationInterface;

#[ORM\Entity(repositoryClass: ProjectRepository::class)]
#[ApiResource(collectionOperations: ['get'],
    itemOperations: ['get'],
    order: ["date" => "DESC"]
)]
class Project implements TranslatableInterface
{
    use TranslatableTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 100)]
    private $image;

    #[ORM\Column(type: 'string', length: 255)]
    private $trailer;

    #[ORM\Column(type: 'string', length: 100)]
    private $pressKit;

    #[ORM\Column(type: 'string', length: 255)]
    private $distributorLink;

    #[ORM\Column(type: 'date')]
    private $date;

    #[ORM\Column(type: 'string', length: 70)]
    private $filmmakerFullName;

    #[ORM\OneToMany(mappedBy: 'project', targetEntity: ProjectThanks::class)]
    private $projectThanks;

    public function __construct()
    {
        $this->projectThanks = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getTrailer(): ?string
    {
        return $this->trailer;
    }

    public function setTrailer(string $trailer): self
    {
        $this->trailer = $trailer;

        return $this;
    }

    public function getPressKit(): ?string
    {
        return $this->pressKit;
    }

    public function setPressKit(string $pressKit): self
    {
        $this->pressKit = $pressKit;

        return $this;
    }

    public function getDistributorLink(): ?string
    {
        return $this->distributorLink;
    }

    public function setDistributorLink(string $distributorLink): self
    {
        $this->distributorLink = $distributorLink;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getFilmmakerFullName(): ?string
    {
        return $this->filmmakerFullName;
    }

    public function setFilmmakerFullName(string $filmmakerFullName): self
    {
        $this->filmmakerFullName = $filmmakerFullName;

        return $this;
    }

    public function getTitle(): string
    {
        return $this->translate()->getTitle();
    }

    public function getDescription(): ?string
    {
        return $this->translate()->getDescription();
    }

    public function getSection1Title(): ?string
    {
        return $this->translate()->getSection1Title();
    }

    public function getSection1Text(): ?string
    {
        return $this->translate()->getSection1Text();
    }

    public function getSection2Title(): ?string
    {
        return $this->translate()->getSection2Title();
    }

    public function getSection2Text(): ?string
    {
        return $this->translate()->getSection2Text();
    }

    /**
     * @return Collection<int, ProjectThanks>
     */
    public function getProjectThanks(): Collection
    {
        return $this->projectThanks;
    }

    public function addProjectThank(ProjectThanks $projectThank): self
    {
        if (!$this->projectThanks->contains($projectThank)) {
            $this->projectThanks[] = $projectThank;
            $projectThank->setProject($this);
        }

        return $this;
    }

    public function removeProjectThank(ProjectThanks $projectThank): self
    {
        if ($this->projectThanks->removeElement($projectThank)) {
            // set the owning side to null (unless already changed)
            if ($projectThank->getProject() === $this) {
                $projectThank->setProject(null);
            }
        }

        return $this;
    }
}

src/Form/ProjectType.php
<?php

namespace App\Form;

use App\Entity\Project;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Validator\Constraints\File;

class ProjectType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('image', FileType::class, array(
                'mapped' => false,
                'required' => true,
                'constraints' => [
                    new File([
                        'maxSize' => '5120k',
                        'mimeTypes' => [
                            'image/png',
                            'image/jpg',
                            'image/jpeg'
                        ],
                        'mimeTypesMessage' => 'Veuillez télécharger une image valide',
                    ])
                ],
            ))
            ->add('trailer', TextType::class, array(
                'label' => 'Lien vidéo',
                'required' => true
            ))
            ->add('pressKit', FileType::class, array(
                'mapped' => false,
                'label' => 'Dossier Presse',
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize' => '20480k',
                        'mimeTypes' => [
                            'application/pdf',
                            'application/xpdf'
                        ],
                        'mimeTypesMessage' => 'Veuillez télécharger un dossier de presse valide (PDF)',
                    ])
                ],
            ))
            ->add('distributorLink', TextType::class, array(
                'label' => 'Lien ditributeur'
            ))
            ->add('date', DateType::class, array(
                'label' => 'Date'
            ))
            ->add('filmmakerFullName', TextType::class, array(
                'label' => 'Réalisateur'
            ))
            ->add('title', TextType::class, array(
                'mapped' => false,
                'label' => 'Titre'
            ))
            ->add('description', TextareaType::class, array(
                'mapped' => false,
                'label' => 'Description'
            ))
            ->add('section1title', TextType::class, array(
                'mapped' => false,
                'label' => 'Section 1 - Titre (Ex: Scénario)'
            ))
            ->add('section1text', TextareaType::class, array(
                'mapped' => false,
                'label' => 'Section 1 - Texte (Liste) : Faites un retour à la ligne pour un nouvel élément de la liste'
            ))
            ->add('section2title', TextType::class, array(
                'mapped' => false,
                'label' => 'Section 2 - Titre (Ex: Acteurs)'
            ))
            ->add('section2text', TextareaType::class, array(
                'mapped' => false,
                'label' => 'Section 2 - Texte (Liste) : Faites un retour à la ligne pour un nouvel élément de la liste'
            ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Project::class,
        ]);
    }
}

src/Controller/BackOffice/ProjectController.php
<?php

namespace App\Controller\BackOffice;

use App\Entity\Project;
use App\Entity\ProjectThanks;
use App\Form\ProjectType;
use App\Form\ProjectThanksType;
use App\Form\ProjectTranslationType;
use App\Repository\ProjectRepository;
use App\Repository\ProjectThanksRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Helpers\BlobHelper;

#[Route('/project')]
class ProjectController extends AbstractController
{
    #[Route('/', name: 'app_project_index', methods: ['GET'])]
    public function index(ProjectRepository $projectRepository): Response
    {
        return $this->render('project/index.html.twig', [
            'projects' => $projectRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_project_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ProjectRepository $projectRepository, BlobHelper $blobHelper): Response
    {
        $project = new Project();
        $form = $this->createForm(ProjectType::class, $project);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $image = $form->get('image')->getData();
            if ($image) {
                $newFilename = $blobHelper->uploadFile($image, 'projects_directory');
                $project->setImage($newFilename);
            }
            unset($image);

            $pressKit = $form->get('pressKit')->getData();
            if ($pressKit) {
                $newFilename = $blobHelper->uploadFile($pressKit, 'projects_directory');
                $project->setPressKit($newFilename);
            }
            unset($pressKit);

            // Traductions
            $lang = 'fr'; 
            $project->translate($lang)->setTitle($form->get('title')->getData());
            $project->translate($lang)->setDescription($form->get('description')->getData());
            $project->translate($lang)->setSection1Title($form->get('section1title')->getData());
            $project->translate($lang)->setSection1Text($form->get('section1text')->getData());
            $project->translate($lang)->setSection2Title($form->get('section2title')->getData());
            $project->translate($lang)->setSection2Text($form->get('section2text')->getData());

            $projectRepository->add($project, true);

            return $this->redirectToRoute('app_project_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('project/new.html.twig', [
            'project' => $project,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_project_show', methods: ['GET'])]
    public function show(Project $project): Response
    {
        return $this->render('project/show.html.twig', [
            'project' => $project,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_project_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Project $project, ProjectRepository $projectRepository, BlobHelper $blobHelper): Response
    {
        $form = $this->createForm(ProjectType::class, $project);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $image = $form->get('image')->getData();
            if ($image) {
                $newFilename = $blobHelper->uploadFile($image, 'projects_directory');
                $project->setImage($newFilename);
            }
            unset($image);

            $pressKit = $form->get('pressKit')->getData();
            if ($pressKit) {
                $newFilename = $blobHelper->uploadFile($pressKit, 'projects_directory');
                $project->setPressKit($newFilename);
            }
            unset($pressKit);

            // Traductions
            $lang = 'fr'; 
            $project->translate($lang)->setTitle($form->get('title')->getData());
            $project->translate($lang)->setDescription($form->get('description')->getData());
            $project->translate($lang)->setSection1Title($form->get('section1title')->getData());
            $project->translate($lang)->setSection1Text($form->get('section1text')->getData());
            $project->translate($lang)->setSection2Title($form->get('section2title')->getData());
            $project->translate($lang)->setSection2Text($form->get('section2text')->getData());
          
            $projectRepository->add($project, true);

            return $this->redirectToRoute('app_project_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('project/edit.html.twig', [
            'project' => $project,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_project_delete', methods: ['POST'])]
    public function delete(Request $request, Project $project, ProjectRepository $projectRepository, ProjectThanksRepository $projectThanksRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$project->getId(), $request->request->get('_token'))) {
            $projectThanks = $project->getProjectThanks();
            foreach ($projectThanks as $key => $value) {
                $projectThanksRepository->remove($value);
            }

            $projectRepository->remove($project, true);
        }

        return $this->redirectToRoute('app_project_index', [], Response::HTTP_SEE_OTHER);
    }
    #[Route('/{id}/addthanks', name: 'app_project_addthanks', methods: ['GET', 'POST'])]
    public function addThanks(Request $request, Project $project, ProjectThanksRepository $projectThanksRepository): Response
    {
        $projectThanks = new ProjectThanks();
        $projectThanks->setProject($project);
        $form = $this->createForm(ProjectThanksType::class, $projectThanks);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $projectThanksRepository->add($projectThanks, true);

            return $this->redirectToRoute('app_project_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('project/addthanks.html.twig', [
            'project' => $project,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}/managetranslation', name: 'app_project_managetranslation', methods: ['GET', 'POST'])]
    public function manageTranslation(Request $request, Project $project, ProjectRepository $projectRepository): Response
    {
        $form = $this->createForm(ProjectTranslationType::class, $project);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $lang = $request->request->get('lang'); 
            $project->translate($lang)->setTitle($form->get('title')->getData());
            $project->translate($lang)->setDescription($form->get('description')->getData());
            $project->translate($lang)->setSection1Title($form->get('section1title')->getData());
            $project->translate($lang)->setSection1Text($form->get('section1text')->getData());
            $project->translate($lang)->setSection2Title($form->get('section2title')->getData());
            $project->translate($lang)->setSection2Text($form->get('section2text')->getData());

            $projectRepository->add($project, true);

            return $this->redirectToRoute('app_project_index', [], Response::HTTP_SEE_OTHER);
        }

        $langsJson = file_get_contents($this->getParameter('locales_directory') . '/langs.json');
        $allLangs = json_decode($langsJson, true)['allLangs'];

        return $this->render('project/managetranslation.html.twig', [
            'project' => $project,
            'form' => $form->createView(),
            'allLangs' => $allLangs
        ]);
    }
}

templates/project/_delete_form.html.twig
<form method="post" action="{{ path('app_project_delete', {'id': project.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ project.id) }}">
    <button class="btn">Supprimer</button>
</form>

templates/project/_form-edit.html.twig
{{ form_start(form) }}
    {{ form_row(form.image, {required: false}) }}
    {{ form_row(form.trailer, {required: false}) }}
    {{ form_row(form.pressKit) }}
    {{ form_row(form.distributorLink) }}
    {{ form_row(form.date) }}
    {{ form_row(form.filmmakerFullName) }}
    {{ form_row(form.title, {value: project.translations['fr'].title}) }}
    {{ form_row(form.description, {value: project.translations['fr'].description}) }}
    {{ form_row(form.section1title, {value: project.translations['fr'].section1Title}) }}
    {{ form_row(form.section1text, {value: project.translations['fr'].section1Text}) }}
    {{ form_row(form.section2title, {value: project.translations['fr'].section2Title}) }}
    {{ form_row(form.section2text, {value: project.translations['fr'].section2Text}) }}
    <button class="btn">{{ button_label|default('Sauvegarder') }}</button>
{{ form_end(form) }}

templates/project/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Sauvegarder') }}</button>
{{ form_end(form) }}

templates/project/addthanks.html.twig
{% extends 'backoffice.html.twig' %}

{% block title %}Ajouter Remerciement{% endblock %}

{% block page %}
    <h1>Ajouter Remerciement</h1>

    {{ form_start(form) }}
        {{ form_widget(form) }}
        <button class="btn">{{ button_label|default('Sauvegarder') }}</button>
    {{ form_end(form) }}

    <div class="contain-button">
        <a href="{{ path('app_project_index') }}">Retour</a>
    </div>
{% endblock %}

templates/project/edit.html.twig
{% extends 'backoffice.html.twig' %}

{% block title %}Modifier Film{% endblock %}

{% block page %}
    <h1>Modifier Film</h1>

    {{ include('project/_form-edit.html.twig', {'button_label': 'Mettre à jour'}) }}

    <div class="contain-button">

        <a href="{{ path('app_project_index') }}">Retour</a>

        {{ include('project/_delete_form.html.twig') }}

    </div>
{% endblock %}

templates/project/index.html.twig
{% extends 'backoffice.html.twig' %}

{% block title %}Les Films{% endblock %}

{% block page %}
    <h1>Les Films</h1>

    <div class="table-contain">
        <div class="table-scroll">

            <table class="table">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Title</th>
                        <th>Date</th>
                        <th>Réalisateur</th>
                        <th>Lien du distributeur</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for project in projects %}
                    <tr>
                        <td>{{ project.id }}</td>
                        <td>{{ project.translations['fr'].title }}</td>
                        <td>{{ project.date ? project.date|date('Y-m-d') : '' }}</td>
                        <td>{{ project.filmmakerFullName }}</td>
                        <td>{{ project.distributorLink }}</td>
                        <td>
                            <a href="{{ path('app_project_show', {'id': project.id}) }}">Afficher</a>
                            <a href="{{ path('app_project_edit', {'id': project.id}) }}">Modifier</a>
                            <a href="{{ path('app_project_addthanks', {'id': project.id}) }}">Ajouter Remerciement</a>
                            <a href="{{ path('app_project_managetranslation', {'id': project.id}) }}">Ajouter une traduction</a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="8">Pas de résultat</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <div class="contain-button">

    <a href="{{ path('app_project_new') }}">Ajouter un film</a>
    </div>
{% endblock %}

templates/project/managetranslation.html.twig
{% extends 'backoffice.html.twig' %}

{% block title %}Traductions{% endblock %}

{% block javascripts %}
    <script>
        let select;
        let title;
        let description;
        let section1title;
        let section1text;
        let section2title;
        let section2text;
        const translations = [];
        {% for key,translation in project.translations %}
            translations["{{ key }}"] = {
                "title" : "{{ translation.title|e('js') }}",
                "description" : "{{ translation.description|e('js') }}",
                "section1title" : "{{ translation.section1title|e('js') }}",
                "section1text" : "{{ translation.section1text|e('js') }}",
                "section2title" : "{{ translation.section2title|e('js') }}",
                "section2text" : "{{ translation.section2text|e('js') }}",
            };
        {% endfor %}

        window.onload = () => {
            select = document.getElementById('langs-select');
            title = document.getElementById('project_translation_title');
            description = document.getElementById('project_translation_description');
            section1title = document.getElementById('project_translation_section1title');
            section1text = document.getElementById('project_translation_section1text');
            section2title = document.getElementById('project_translation_section2title');
            section2text = document.getElementById('project_translation_section2text');

            select.onchange = () => {
                let lang = select.value;
                
                if (translations[lang])
                {
                    title.value = translations[lang].title;
                    description.value = translations[lang].description;
                    section1title.value = translations[lang].section1title;
                    section1text.value = translations[lang].section1text;
                    section2title.value = translations[lang].section2title;
                    section2text.value = translations[lang].section2text;
                }
            }
        }
    </script>
{% endblock %}

{% block page %}
    <h1>Traductions</h1>

    {{ form_start(form) }}
        <select name="lang" id="langs-select">
            {% for lang in allLangs %}
                <option value="{{ lang }}">{{ lang }}</option>
            {% endfor %}
        </select>
        {{ form_row(form._token) }}
        {{ form_row(form.title, {value : project.translations['fr'].title}) }}
        {{ form_row(form.description, {value : project.translations['fr'].description}) }}
        {{ form_row(form.section1title, {value : project.translations['fr'].section1title}) }}
        {{ form_row(form.section1text, {value : project.translations['fr'].section1text}) }}
        {{ form_row(form.section2title, {value : project.translations['fr'].section2title}) }}
        {{ form_row(form.section2text, {value : project.translations['fr'].section2text}) }}

        <button class="btn">{{ button_label|default('Sauvegarder') }}</button>
    {{ form_end(form, {'render_rest': false}) }}

    <a href="{{ path('app_project_index') }}">Retour</a>
{% endblock %}

templates/project/new.html.twig
{% extends 'backoffice.html.twig' %}

{% block title %}Nouveau film{% endblock %}

{% block page %}
    <h1>Ajouter un Film</h1>

    {{ include('project/_form.html.twig') }}

    <div class="contain-button">

        <a href="{{ path('app_project_index') }}">Retour</a>

    </div>
{% endblock %}

templates/project/show.html.twig
{% extends 'backoffice.html.twig' %}

{% block title %}Film{% endblock %}

{% block page %}
    <h1>Film</h1>

    <div class="table-contain">
        <div class="table-scroll">

            <table class="table">
                <tbody>
                    <tr>
                        <th>Id</th>
                        <td>{{ project.id }}</td>
                    </tr>
                    <tr>
                        <th>Titre</th>
                        <td>{{ project.translations['fr'].title }}</td>
                    </tr>
                    <tr>
                        <th>Description</th>
                        <td>{{ project.translations['fr'].description }}</td>
                    </tr>
                    <tr>
                        <th>{{ project.translations['fr'].section1title }}</th>
                        <td>{{ project.translations['fr'].section1text }}</td>
                    </tr>
                    <tr>
                        <th>{{ project.translations['fr'].section2title }}</th>
                        <td>{{ project.translations['fr'].section2text }}</td>
                    </tr>
                    <tr>
                        <th>Image</th>
                        <td><img src="/uploads/projects/{{ project.image }}" alt="Poster of movie" width="300" /></td>
                    </tr>
                    <tr>
                        <th>Trailer</th>
                        <td>{{ project.trailer }}</td>
                    </tr>
                    <tr>
                        <th>Dossier de presse</th>
                        <td><a href="/uploads/projects/{{ project.pressKit }}" download>Download</a></td>
                    </tr>
                    <tr>
                        <th>Lien du distributeur</th>
                        <td>{{ project.distributorLink }}</td>
                    </tr>
                    <tr>
                        <th>Date</th>
                        <td>{{ project.date ? project.date|date('Y-m-d') : '' }}</td>
                    </tr>
                    <tr>
                        <th>Réalisateur</th>
                        <td>{{ project.filmmakerFullName }}</td>
                    </tr>
                    {% if project.projectThanks|length > 0 %}
                    <tr>
                        <th>Remerciements</th>
                        <td>
                            <ul>
                            {% for thanks in project.projectThanks %}
                                <li>{{ thanks.name }}</li>
                            {% endfor %}
                            <ul>
                        </td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>

    <div class="contain-button">

        <a href="{{ path('app_project_index') }}">Retour</a>

        <a href="{{ path('app_project_edit', {'id': project.id}) }}">Modifier</a>
        
        <a href="{{ path('app_project_addthanks', {'id': project.id}) }}">Ajouter remerciement</a>
        
        <a href="{{ path('app_project_managetranslation', {'id': project.id}) }}">Traductions</a>

        {{ include('project/_delete_form.html.twig') }}

    </div>
{% endblock %}